# -*- coding: utf-8 -*-
"""Vikram_Rajpurohit_Resume.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19tcVpP2MGYaNnsTJRNtkXbm5a1ttRBDn

# Vikram Rajpurohit

##                      **Cover Letter**

            As a Data Science Enthusiast, I feel privileged to have found this opportunity to apply as a data analyst in a 
            meaningful industry and a passionate company. As a continuous follower of the science & analytics field, 
            my qualifications align with the practical and technical skills that Company seeks.Being an ardent reader of 
            Tech Startup news and analyzing the Business Forecasting gives me immense pleasure.


            I just love the whole process of gathering and interpreting data from a variety of sources to help the
            organization improve the quality of sales and enhance the customer experience. Coming from a Technical
            Support background I understand how much important data plays a role in business strategy and how it can
            be elevated to improve the customer experience in Sales, Customer Retention and Project planning.


            I would be thrilled ve a part of your esteemed company where my work would be highly beneficial to the
            organization. Please refer to my attached resume for additional information regarding my proficiencies and
            achievements. Given an opportunity, I can assure you that I would be a valuable employee over the years to come.

            Thank you for your time and consideration.
            Yours sincerely,
            Vikram BhawarSingh Rajpurohit.

### Resume
- Name: Vikram B Rajpurohit
- <a href="imvikramraj95@gmail.com">Email ID</a>
- Phone: 7021800020 / 8976674161
<img src="https://1000logos.net/wp-content/uploads/2017/03/Linkedin-Logo.png"  width="50"/>

- <a href="https://www.linkedin.com/in/vikram-rajpurohit-a486b17a">LinkedIn</a>                                                                  

  <img src="https://image.flaticon.com/icons/png/512/25/25231.png"  width="50"/>

- <a href="https://github.com/vikramrajja">GitHub</a>

  <img src="https://cdn4.iconfinder.com/data/icons/social-media-icons-the-circle-set/48/twitter_circle-512.png"  width="50"/>

- <a href="https://twitter.com/imvikramraj">Twitter</a>

  <img src="https://cdn1.iconfinder.com/data/icons/social-media-circle-7/512/Circled_Medium_svg5-512.png"  width="50"/>

- <a href="https://medium.com/@vikramraj">Medium</a>

  <img src="https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/189_Kaggle_logo_logos-512.png"  width="50"/>

- <a href="https://www.kaggle.com/iamvikramraj">Kaggle</a>

###Skills
- Programming languages
    - Python (Data Science Lib)
    - SQL (moderate)
    - Bash\Linux (Hands-on)
    - HTML/CSS (working knowledge)
- Libraries
    - Python
        - Numpy
        - Pandas
        - sklearn
        - matplotlib
        - Scipy
        - Anaconda
- IDEs
    - Spyder
    - Jupyter Notebook
    - Terminal
- Version Control Systems
    - Git / GitHub
- Databases
    - MySQL
- Operating Systems
    - Windows 7/8/8.1/10
    - Fedora 16.04
    - Mac OS
- Soft skills
    - Self-taught everything, can learn anything quickly
    - Easy to get along with, friendly
--------------------------------------------------------------------------------

## Qualification 

--------------------------------------------------------------------------------

|Institute Level|Percentage (CGPA)|
|------|------|
|SSC   |92.73%    |
|Diploma     |86.34%     |
|Degree (B.E in Comp)| 6.78 CGPA (58%)

--------------------------------------------------------------------------------

### Work Experience (3 Years)

--------------------------------------------------------------------------------

- Assistant System Engg at TCS from Nov 2016 to Dec 2017
   - Worked at Startup from Jan 2018 to June 2018 (Ultraskills)
   - Senior Support Engg at Tech M from July 2018 to April 2019
   - Worked as SEM at Wipro on Pilot Project from July 2019 to Dec 2019
   - Currently at ZS Associates (Jan 2012 - )

--------------------------------------------------------------------------------

### Projects

--------------------------------------------------------------------------------

#### **Predicting the Bank Customer Churn DataSet**

- Tools Used- Python, Machine Learning
- Bank Customer Data Set study and Visualization.
- User Behaviour study using services used
- Applying Technique for Dataset Balancing and other technique
- Using different algo for Better accuracy like Log Reg, Random
Forest and Decision Tree
- Link: https://github.com/vikramrajj/Capstone-Project/blob/main/Capstone_1.ipynb


#### **Predicting the Travel Insurance Opt-in DataSet**
- Travel Insurance Data Set study and Visualization.
- Travel Booking and Insurance Opt-in Pattern
- Applying Technique for Dataset Balancing and other technique
- Using different algo for Better accuracy like Random Forest ,
Adaboost etc.
- Link: https://github.com/vikramrajj/Capstone-Project/blob/main/Capstone_2.ipynb

--------------------------------------------------------------------------------

### Interests

--------------------------------------------------------------------------------
- Games
    - Clash of Clan (Strategy) 
- Sports
    - Cricket algorithms and analysis
    - Reading Historical Novels
- Writing & Reading
    - Well Researched Article
    - Links :
     * https://www.startup-buzz.com/singles-day-alibaba-hits-double-figures-hours/ (Freelance)
     * https://www.startup-buzz.com/ola-cabs-aims-profitability-2019/ (Frelance)

--------------------------------------------------------------------------------

### Awards

--------------------------------------------------------------------------------
- Technical Paper Presentation State level event based on NFC.
- Elected as General Secretary for College cultural Event
Consecutive year.
"""

